# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-alpine

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir mcp

# Copy server script
COPY mcp_server /app/mcp_server
RUN chmod +x /app/mcp_server

# Start the MCP server
CMD ["python", "/app/mcp_server"]
